# Generated by Django 2.2.6 on 2019-11-01 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='item_image',
            field=models.CharField(default='https://s3.amazonaws.com/ODNUploads/5639404dd09eeplaceholder_food_item_2.png', max_length=500),
        ),
    ]
