# Generated by Django 2.2.6 on 2019-11-01 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0002_item_item_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='item_image',
            field=models.CharField(default='https://wurtsmithairmuseum.net/wp-content/uploads/2018/10/Image_Coming_Soon.jpg', max_length=500),
        ),
    ]
