# Generated by Django 2.2.6 on 2020-10-05 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0002_task_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='image',
            field=models.ImageField(default='Images/None/NoImg.jpg', upload_to='images/'),
        ),
    ]
